require: rubocop-rspec

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'
    - 'spec/views/**/*'
    - 'spec/lint/rubocop_spec\.rb'

RSpec/MultipleExpectations:
  Max: 5

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 50

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/rails_helper\.rb'
    - 'spec/spec_helper\.rb'
