---
version: 2
jobs:
  build:
    working_directory: ~/CaringForKarenSue-Rails
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: CaringForKarenSue-Rails-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: CaringForKarenSue-Rails-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Setup the database
      - run: bundle exec rails db:setup

      # Run the tests
      - run: bundle exec rspec
